include_directories(${CMAKE_CURRENT_LIST_DIR})

set(XMODEL_BINARY_SOURCES
    ${XMODEL_BINARY_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_archiverecords.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_archiverecords.h
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_fparts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_fparts.h
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_hex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_hex.h
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_streams.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_streams.h
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_ximport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_ximport.h
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_xexport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_xexport.h
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_xsymbol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_xsymbol.h
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_xresource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmodel_xresource.h
)
